<?php
    $sales = $data['sales'];
    $busSales = $data['busSales'];
    $salesToDate = $data['salesToDate'];
    $schedules = $data['schedules'];
?>
<div class="admin container my-5">
    <h1 class="mb-5">Dashboard</h1>
    <div class="content">
        <div class="row align-items-stretch">
            <div class="c-dashboardInfo col-lg-4 col-md-6" onclick="goto('buses')">
                <div class="wrap">
                    <h2 class="heading heading5 hind-font medium-font-weight c-dashboardInfo__title">Buses<svg
                        class="MuiSvgIcon-root-19" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                        <path fill="none" d="M0 0h24v24H0z"></path>
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"></path>
                        </svg>
                    </h2>
                    <span class="hind-font caption-12 c-dashboardInfo__count"><?= count($busSales) ?></span>
                    <div class="details-container">
                        <?php foreach ($busSales as $busSale) : ?>
                            <div class="card">
                                <div class="card-body d-flex justify-content-between">
                                    <div >Bus #: <strong><?= $busSale->bus_number ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div class=""><strong>Php <?= number_format($busSale->total_sales, 2, '.', ',') ?></strong></div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="c-dashboardInfo col-lg-4 col-md-6" onclick="goto('reservations')">
                <div class="wrap">
                    <h2 class="heading heading5 hind-font medium-font-weight c-dashboardInfo__title">Reservations<svg
                        class="MuiSvgIcon-root-19" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                        <path fill="none" d="M0 0h24v24H0z"></path>
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"></path>
                        </svg>
                    </h2>
                    <span class="hind-font caption-12 c-dashboardInfo__count"><?= count($data['reservations']) ?></span>
                    <div class="details-container">
                        <?php foreach ($data['reservations'] as $reservation) : ?>
                            <div class="card">
                                <div class="card-body d-flex justify-content-between">
                                    <div><strong><?= $reservation->dates ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div>Bus #: <strong><?= $reservation->bus_number ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div class=""><strong>Php <?= number_format($reservation->price, 2, '.', ',') ?></strong></div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="c-dashboardInfo col-lg-4 col-md-6" onclick="goto('reservations')">
                <div class="wrap">
                    <h2 class="heading heading5 hind-font medium-font-weight c-dashboardInfo__title">Sales<svg
                        class="MuiSvgIcon-root-19" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                        <path fill="none" d="M0 0h24v24H0z"></path>
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"> </path>
                        </svg>
                    </h2>
                    <span class="hind-font caption-12 c-dashboardInfo__count">Php <?= number_format($sales->total_sales, 2, '.', ',') ?></span>
                    <div class="details-container">
                        <?php foreach ($salesToDate as $toDate) : ?>
                            <div class="card">
                                <div class="card-body d-flex justify-content-between">
                                    <div><strong><?= $toDate->dates ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div class=""><strong>Php <?= number_format($toDate->total_sales, 2, '.', ',') ?></strong></div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="c-dashboardInfo col-lg-12" onclick="goto('schedules')">
                <div class="wrap">
                    <h2 class="heading heading5 hind-font medium-font-weight c-dashboardInfo__title">Schedules<svg
                        class="MuiSvgIcon-root-19" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                        <path fill="none" d="M0 0h24v24H0z"></path>
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"></path>
                        </svg>
                    </h2>
                    <!-- <span class="hind-font caption-12 c-dashboardInfo__count"><?= count($schedules) ?></span> -->
                    <div class="details-container large mt-5">
                        <?php foreach ($schedules as $schedules) : ?>
                            <div class="card">
                                <div class="card-body d-flex justify-content-between">
                                    <div >Bus #: <strong><?= $schedules->bus_number ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div >Routes: <strong><?= $schedules->routes ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div >Dep: <strong><?= $schedules->dept_time ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div >Arr: <strong><?= $schedules->arrival_time ?></strong></div>
                                    <div><strong> | </strong></div>
                                    <div class=""><strong>Php <?= number_format($schedules->price, 2, '.', ',') ?></strong></div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function goto(location) {
        document.location = `/chabeebus/public/${location}`;
    }
</script>