<?php
    $schedules = $data['schedules'];
?>

<div class="container my-5">
    <?php if (is_array($schedules) && count($schedules) > 0) : ?>
        <?php foreach ($schedules as $schedule) : ?>
            <div class="card bg-light bus-item mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-9 p-5">
                            <div class="row">
                                <div class="col-6">
                                    <span class="col-7"><strong>Bus No: </strong></span>
                                    <span class="col-5"><?= $schedule->bus_number ?></span>
                                </div>
                                <div class="col-6">
                                    <span class="col-7"><strong>Departure:</strong></span>
                                    <span class="col-5"><?= $schedule->dept_time ?> </span>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-6">
                                    <span class="col-7"><strong>Available Seats: </strong></span>
                                    <span class="col-5">test</span>
                                </div>
                                <div class="col-6">
                                    <span class="col-7"><strong>Arrival Time: </strong></span>
                                    <span class="col-5"><?= $schedule->arrival_time ?> </span>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-3">
                            <!-- <div class="img-container">
                                <img src=<php $row['busImage'] ?> alt="bus-image">
                            </div> -->
                        </div>
                    </div>
                                                    
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>