 <!-- booking section starts -->
<section class="admin container booking">
    <h1 class="heading title mb-3">book your trip!</h1>
    <div class="content">
        <form action="book/save" method="post" class="book-form">
            <div class="flex">

                <div class="inputBox">
                    <span>Date :</span>
                    <input type="date" name="reserveDate">
                </div>

                <div class="inputBox">
                        <span>location :</span>
                            <input type="text" placeholder="Enter location" name="location">
                </div>

            </div>
            <button type="submit" class="btn btn-outline-secondary btn-lg mt-3">Submit</button>
        </form>
    </div>
</section>
<!-- booking section ends -->
 