 <!-- booking section starts -->
 <section class="booking">
            <h1 class="heading title">book your trip!</h1>

            <form action="book/save" method="post" class="book-form">

                <div class="flex">

                    <div class="inputBox">
                        <span>Date :</span>
                        <input type="date" name="reserveDate">
                    </div>

                    <div class="inputBox">
                            <span>location :</span>
                                <input type="text" placeholder="Enter location" name="location">
                    </div>

                </div>
                <button type="submit" class="btn btn-outline-secondary btn-lg">Submit</button>
            </form>
        </section>
        <!-- booking section ends -->