<section class="admin container">
    <div class="content">
        <?php if (is_array($data['buses'])) : ?>
            <?php foreach ($data['buses'] as $bus) : ?>
                <div class="card bg-light bus-item mb-3">
                    <?php
                        $db = new Database();
                        $reservations = $db->read("SELECT * from reservations WHERE bus_number = ". $bus->bus_number);
                    ?>
                    <div class="card-body" type="submit" name="reservation">
                        <?php echo '<div class="row" onclick="showTable('. $bus->bus_number .')">' ?>    
                            <div class="col-9 p-5">
                                <div class="row">
                                    <div class="col-6">
                                        <span class="col-7"><strong>Bus No: </strong></span>
                                        <span class="col-5"><?= $bus->bus_number ?></span>
                                    </div>
                                    <div class="col-6">
                                        <span class="col-7"><strong>Location:</strong></span>
                                        <span class="col-5">test</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <span class="col-7"><strong>Available Seats: </strong></span>
                                        <span class="col-5"><?= $bus->capacity - count($reservations). "/" .$bus->capacity; ?></span>
                                    </div>
                                    <div class="col-6">
                                        <span class="col-4"><strong>Route:</strong></span>
                                        <span class="col-8">test</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <span class="col-4"><strong>Driver: </strong></span>
                                        <span class="col-4">test</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <span class="col-4"><strong>Conductor: </strong></span>
                                        <span class="col-4">test</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="img-container">
                                    <?php echo '<img src="'. $bus->busImage .'" alt="bus-image">' ?>
                                </div>
                            </div>
                        </div>
                        <!-- reservations -->
                        <?php echo '<div class="table-container border-top" id="busItem'. $bus->bus_number .'">' ?>
                            <?php if (is_array($reservations) && count($reservations) > 0) : ?>
                                <div class="card">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th scope="col">Seat #</th>
                                                <th scope="col">Passenger Name</th>
                                                <th scope="col">Status</th>
                                                <th scope="col">Available</th>
                                                <th scope="col"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($reservations as $reservation) : ?>
                                            <tr>
                                                <th scope="row"><?= $reservation->seat_number; ?></th>
                                                <td><?= $reservation->passenger_name; ?></td>
                                                <td><?= $reservation->paid ? 'Paid' : ''; ?></td>
                                                <td><?= $reservation->paid ? 'No' : 'Yes'; ?></td>
                                                <td class="row">
                                                    <form action="<?= "reservations/delete/". $reservation->reservation_id ?>" method="POST">
                                                        <input type="hidden" name="delete" value="<?= $reservation->reservation_id ?>">
                                                        <span><button class="btn btn-sm btn-danger">&times;</button></span>
                                                    </form>
                                                </td>
                                            </tr>
                                            <?php endforeach ?>
                                        </tbody>
                                    </table>
                                </div>
                            <?php else : ?>
                                <div class="card text-center">
                                    <p>No Reservations Found</p>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</section>

<script type="text/javascript">
    const showTable = (index) => {
        const tableEl = document.getElementById(`busItem${index}`);
        if (tableEl) {
            if (tableEl.classList.contains('show')) {
                tableEl.classList.remove('show');
            } else {
                tableEl.classList.add('show');
            }
        }
    };
</script>