    <!-- home section starts -->
    <section class="home">
        <div class="swiper home-slider">
                <div class="swiper-wrapper">
                    <div class="swiper-slide slide" style="background: url(<?=ASSETS?>img/busmeta.png) no-repeat;">
                        <div class="content">
                            <span style="color: White;
                        -webkit-text-stroke:1px black;
                        -webkit-text-fill-color:White;">explore, discover, travel</span>
                            <h3 style="color: White;
                            -webkit-text-stroke:1px black;
                            -webkit-text-fill-color:White;">Travel with us</h3>
                            <a href="book.php" class="btn">Book Now</a>
                        </div>
                    </div>

                    <div class="swiper-slide slide" style="background: url(<?=ASSETS?>img/bluredd.png) no-repeat;">
                        <div class="content">
                        <span style="color: White;
                        -webkit-text-stroke:1px black;
                        -webkit-text-fill-color:White;">explore, discover, travel</span>
                        <h3 style="color: White;
                        -webkit-text-stroke:1px black;
                        -webkit-text-fill-color:White;">Travel to new places</h3>
                        <a href="package.php" class="btn">Discover more</a>
                        </div>
                    </div>
                
                    <div class="swiper-slide slide" style="background: url(<?=ASSETS?>img/blurbusbg3.jpg) no-repeat;">
                        <div class="content">
                            <span style="color: White;
                        -webkit-text-stroke:1px black;
                        -webkit-text-fill-color:White;">explore, discover, travel</span>
                            <h3 style="color: White;
                        -webkit-text-stroke:1px black;
                        -webkit-text-fill-color:White;">Make your tour worthwhile</h3>
                            <a href="package.php" class="btn">Discover more</a>
                        </div>
                    </div>
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
    </section>
    <!-- home section ends -->

    <!-- Services Section starts -->
    <section class="services">
        <h1 class="heading-title">Our Services</h1>

        <div class="box-container">
            <div class="box">
                <img src="<?=ASSETS?>img/adven.png" alt="">
                <h3>Adventure</h3>
            </div>
            
            <div class="box">
                <img src="<?=ASSETS?>img/tourist.png" alt="">
                <h3>Tour</h3>
            </div> 

            <div class="box">
                <img src="<?=ASSETS?>img/trekking.png" alt="">
                <h3>Trekking</h3>
            </div> 

            <div class="box">
                <img src="<?=ASSETS?>img/campfire.png" alt="">
                <h3>Camp fire</h3>
            </div> 

            <div class="box">
                <img src="<?=ASSETS?>img/offroad.png" alt="">
                <h3>Off road</h3>
            </div>

            <div class="box">
                <img src="<?=ASSETS?>img/camping.png" alt="">
                <h3>Camping</h3>
            </div> 
        </div>
    </section>
    <!-- Services Section ends -->

    <!-- home about section starts -->
    <section class="home-about">
        <div class="image">
            <img src="<?=ASSETS?>img/aboutbus.png" alt="">
        </div>

        <div class="content">
            <h3>About us</h3>
            <p>It is a long established fact that a reader will be distracted 
                by the readable content of a page when looking at its layout. 
                The point of using Lorem Ipsum is that it has a more-or-less 
                normal distribution of letters, as opposed to using 'Content 
                here, content here', making it look like readable English. 
            </p>
            <a href="about.php" class="btn">read more</a>
        </div>
    </section>
    <!-- home about section ends -->

    <!-- home packages section starts -->
    <section class="home-packages">

        <h1 class="heading-title">Our Packages</h1>

        <div class="box-container">

            <div class="box">
                <div class="image">
                    <img src="<?=ASSETS?>img/schoolbus.jpg" alt="">
                </div>
                <div class="content">
                    <h3>Travel and Tour</h3>
                    <p>It is a long established fact that a reader will be distracted.</p>
                    <a href="book.php" class="btn">book now</a>
                </div>
            </div>

            <div class="box">
                <div class="image">
                    <img src="<?=ASSETS?>img/schoolbus2.jpg" alt="">
                </div>
                <div class="content">
                    <h3>Travel and Tour</h3>
                    <p>It is a long established fact that a reader will be distracted.</p>
                    <a href="book.php" class="btn">book now</a>
                </div>
            </div>

            <div class="box">
                <div class="image">
                    <img src="<?=ASSETS?>img/schoolbus3.jpg" alt="">
                </div>
                <div class="content">
                    <h3>Travel and Tour</h3>
                    <p>It is a long established fact that a reader will be distracted.</p>
                    <a href="book.php" class="btn">book now</a>
                </div>
            </div>


        </div>
            <div class="load-more"><a href="package.php" class="btn">Load more</a></div>
        </div>
    </section>
    <!-- home packages section ends  -->

    <!-- home offer section starts -->
    <section class="home-offer">
        <div class="content">
            <h3>upto 50% off</h3>

            <p>It is a long established fact that a reader will be distracted 
                by the readable content of a page when looking at its layout.
            </p>

                <a href="book.php" class="btn">book now</a>
        </div>
    </section>
    <!-- home offer section ends -->