<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $data['title']; ?></title>
    
    <!-- swiper css link -->
    <link rel="stylesheet" href="<?=ASSETS?>/styles/bootstrap.min.css"/>

    <!-- swiper css link -->
    <link rel="stylesheet" href="<?=ASSETS?>/styles/swippper.css"/>

    <!-- font awesome cdn link -->
    <link rel="stylesheet" href="<?=ASSETS?>/styles/font-awesome.css">

    <!-- Custom CSS Styling -->
    <link rel="stylesheet" href="<?=ASSETS?>/styles/styles.css">
</head>
<body>
    <div class="container">
        <h1>This is <?= $data['title']; ?></h1>
    </div>


    <!-- scripts -->
    <script src="<?=ASSETS?>/js/bootstrap-bundle.min.js"></script>
    <script src="<?=ASSETS?>/js/swiper-bundle.min.js"></script>
</body>
</html>