 <!-- booking section starts -->
 <?php $schedule = $data['schedule'];?>
 <section class="booking">
            <h1 class="heading title">Reservation Form</h1>

            <form action="book/save" method="post" class="book-form">

                <div class="flex">

                    <div class="inputBox">
                        <span>Date :</span>
                        <input type="date" name="reserveDate" value="<?= $data['date'] ?>" readonly>
                    </div>

                    <div class="inputBox">
                            <span>Bus # :</span>
                            <input type="number" value="<?= $schedule->bus_number ?>" name="busNo" readonly>
                    </div>

                    <div class="inputBox">
                            <span>Location :</span>
                            <input type="text" value = "<?= $schedule->location ?> " name="location" readonly>
                    </div>
                    
                    <div class="inputBox">
                            <span>Departure :</span>
                            <input type="time" value="<?= $schedule->dept_time ?>" name="departure" readonly>
                    </div>
                    
                    <div class="inputBox">
                            <span>Arrival :</span>
                            <input type="time" value="<?= $schedule->arrival_time ?>" name="arrival" readonly>
                    </div>
                   
                    <div class="inputBox">
                        <span>Seat Number :</span>
                        <input type="number" name="seatNumber">
                    </div>

                    <div class="inputBox"></div>
                    <div class="inputBox"></div>
                

                </div>
                <button type="submit" class="btn btn-outline-secondary btn-lg">Submit</button>
            </form> 
        </section>
        <!-- booking section ends -->