<?php
    $schedules = $data['schedules']; 
?>
<div class="admin container my-5">
    <div class="content">
        <h1 class="mb-5">Schedules</h1>
        <div class="card">
            <div class="card-body">
                <?php if (is_array($schedules) && count($schedules) > 0) : ?>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Bus #</th>
                                <th scope="col">Routes</th>
                                <th scope="col">Departure</th>
                                <th scope="col">Arrival</th>
                                <th scope="col">Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($schedules as $schedule) : ?>
                            <tr>
                                <th scope="row"><?= $schedule->bus_number ?></th>
                                <td><?= $schedule->routes ?></td>
                                <td><?= $schedule->dept_time ?></td>
                                <td><?= $schedule->arrival_time ?></td>
                                <td><?= $schedule->price ?></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <div class="card my-5 p-3">
                        <h1 class="text-center">No Schedules Found</h1>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>