 <!-- footer section starts -->
 <section class="footer">
        <div class="box-container">
            <div class="box">
                <h3>Quick Links</h3>
                <a href="buses"><i class="fas fa-angle-right "></i>Buses</a>
                <a href="schedules"><i class="fas fa-angle-right "></i>Schedules</a>
                <a href="reservations"><i class="fas fa-angle-right "></i>Reservations</a>
                <a href="home"><i class="fas fa-angle-right "></i>Home</a>
            </div>

            <div class="box">
                <h3>Extra Links</h3>
                <a href="#"><i class="fas fa-angle-right "></i>Ask Questions</a>
                <a href="#"><i class="fas fa-angle-right "></i>About us</a>
                <a href="#"><i class="fas fa-angle-right "></i>Privacy Policy</a>
                <a href="#"><i class="fas fa-angle-right "></i>Terms of use</a>
            </div>
            
            <div class="box">
                <h3>Contact Info</h3>
                <a href="#"><i class="fas fa-phone "></i>+639-518-152-728</a>
                <a href="#"><i class="fas fa-phone "></i>+639-518-152-728</a>
                <a href="#"><i class="fas fa-envelope"></i>email@gmail.com</a>
                <a href="#"><i class="fas fa-map "></i>Davao City, Philippines</a>            
            </div>

            <div class="box">
                <h3>follow us</h3>
                <a href="#"> <i class="fab fa-facebook-f "></i>facebook</a>
                <a href="#"> <i class="fab fa-twitter"></i>twitter</a>
                <a href="#"> <i class="fab fa-instagram"></i>instagram</a>
                <a href="#"> <i class="fab fa-linkedin"></i> linkedin</a>
            </div>
        </div>

        <div class="credit"> created by <span>euniquecorn</span> | all rights reserved
        </div>
    </section>
    <!-- footer section ends -->
</body>
</html>