 <!-- footer section starts -->
 <section class="footer px-5 py-3 pb-1">
        <div class="box-container d-flex justify-content-evenly">
            <div class="box">
                <h3>Quick Links</h3>
                <a href="/home"><i class="fas fa-angle-right "></i>Home</a>
                <a href="/about"><i class="fas fa-angle-right "></i>About us</a>
                <a href="/book"><i class="fas fa-angle-right "></i>Book</a>
                <a href="/admin"><i class="fas fa-angle-right "></i>Admin</a>
            </div>

            <div class="box">
                <h3>Extra Links</h3>
                <a href="#"><i class="fas fa-angle-right "></i>Ask Questions</a>
                <a href="#"><i class="fas fa-angle-right "></i>About us</a>
                <a href="#"><i class="fas fa-angle-right "></i>Privacy Policy</a>
                <a href="#"><i class="fas fa-angle-right "></i>Terms of use</a>
            </div>
            
            <div class="box">
                <h3>Contact Info</h3>
                <a href="#"><i class="fas fa-phone "></i>+639-518-152-728</a>
                <a href="#"><i class="fas fa-phone "></i>+639-518-152-728</a>
                <a href="#"><i class="fas fa-envelope"></i>email@gmail.com</a>
                <a href="#"><i class="fas fa-map "></i>Davao City, Philippines</a>            
            </div>

            <div class="box">
                <h3>follow us</h3>
                <a href="#"> <i class="fab fa-facebook-f "></i>facebook</a>
                <a href="#"> <i class="fab fa-twitter"></i>twitter</a>
                <a href="#"> <i class="fab fa-instagram"></i>instagram</a>
                <a href="#"> <i class="fab fa-linkedin"></i> linkedin</a>
            </div>
        </div>

        <div class="credit"> created by <span>euniquecorn</span> | all rights reserved
        </div>
    </section>
    <!-- footer section ends -->
</body>
</html>