<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $data['page_title']; ?></title>
    
    <!-- swiper css link -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/bootstrap.min.css"/>

    <!-- swiper css link -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/swiper.css"/>

    <!-- font awesome cdn link -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/font-awesome.css">

    <!-- Custom CSS Styling -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/styles.css">
</head>
<body>
    <!-- header section starts -->
    <section class="header">
        <a class="logo" href="/home">ChaBeeBus</a>

        <nav class="navbar">
            <a href="./home">Home</a>
            <a href="./about">About us</a>
            <a href="./book">Book</a>
            <a href="./admin">Admin</a>
        </nav>

        <div id="menu-btn" class="fas fa-bars"></div>
    </section>
    <!-- header section ends -->