<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $page_title ?></title>
    
    <!-- swiper css link -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/bootstrap.min.css"/>

    <!-- swiper css link -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/swiper.css"/>

    <!-- font awesome cdn link -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/fontawesome.css">

    <!-- Custom CSS Styling -->
    <link rel="stylesheet" href="<?=ASSETS?>styles/styles.css">

    <!-- scripts -->
    <script type="text/javascript" src="<?=ASSETS?>js/bootstrap-bundle.min.js"></script>
    <script type="text/javascript" src="<?=ASSETS?>js/swiper-bundle.min.js"></script>
</head>
<body>
    <!-- header section starts -->
    <section class="header">
        <a class="logo" href="/home">ChaBeeBus</a>

        <nav class="navbar">
            <a href="./home">Buses</a>
            <a href="./about">Schedules</a>
            <a href="./book">Bookings</a>
            <a href="./home">Home</a>
        </nav>

        <div id="menu-btn" class="fas fa-bars"></div>
    </section>
    <!-- header section ends -->